export const JOB = {
  SEND_MAIL_TO_CANDIDATE: 'SEND_MAIL_TO_CANDIDATE',
  SEND_MAIL_TO_RECRUITER: 'SEND_MAIL_TO_RECRUITER',
  SEND_OTP_MAIL_TO_USER: 'SEND_OTP_MAIL_TO_USER',
  SEND_RESET_MAIL_TO_USER: 'SEND_RESET_MAIL_TO_USER',
};
